version: 0.0.{build}

branches:
  only:
    - master

skip_non_tags: true

image: Visual Studio 2019
platform: x64

environment:
  BUILD: true
  PYPI_PASSWORD:
    secure: bBLT+ICiuwrkYZEBrL++Jw==

  matrix:
    - PYTHON: "C:\\Python38"
      SOURCE: "TRUE"

    - PYTHON: "C:\\Python38"
      PYTHON_VERSION: "3.8.x"
      PYTHON_ARCH: "32"
      LIBTGVOIP_JOB: "Environment: PLATFORM=x86"

    - PYTHON: "C:\\Python38-x64"
      PYTHON_VERSION: "3.8.x"
      PYTHON_ARCH: "64"
      LIBTGVOIP_JOB: "Environment: PLATFORM=x64"

    - PYTHON: "C:\\Python37"
      PYTHON_VERSION: "3.7.x"
      PYTHON_ARCH: "32"
      LIBTGVOIP_JOB: "Environment: PLATFORM=x86"

    - PYTHON: "C:\\Python37-x64"
      PYTHON_VERSION: "3.7.x"
      PYTHON_ARCH: "64"
      LIBTGVOIP_JOB: "Environment: PLATFORM=x64"

    - PYTHON: "C:\\Python36"
      PYTHON_VERSION: "3.6.x"
      PYTHON_ARCH: "32"
      LIBTGVOIP_JOB: "Environment: PLATFORM=x86"

    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6.x"
      PYTHON_ARCH: "64"
      LIBTGVOIP_JOB: "Environment: PLATFORM=x64"

    - PYTHON: "C:\\Python35"
      PYTHON_VERSION: "3.5.x"
      PYTHON_ARCH: "32"
      LIBTGVOIP_JOB: "Environment: PLATFORM=x86"

    - PYTHON: "C:\\Python35-x64"
      PYTHON_VERSION: "3.5.x"
      PYTHON_ARCH: "64"
      LIBTGVOIP_JOB: "Environment: PLATFORM=x64"



clone_folder: c:\projects\pytgvoip

cache:
  - ../openssl_1_1_1 -> ci_scripts/01-openssl.bat
  - ../opus -> ci_scripts/02-opus.bat

init:
  - if "%PYTHON_ARCH%"=="32" call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars32.bat"
  - if "%PYTHON_ARCH%"=="64" call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat"

install:
  - ps: if (-not(Test-Path($env:PYTHON))) { & ci_scripts\install.ps1 }
  - set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
  - python --version
  - python -c "import struct; print(struct.calcsize('P') * 8)"
  - python -m pip install wheel pip twine -U

  - git submodule update --init --recursive

build_script:
  - if not "%SOURCE%"=="TRUE" ci_scripts\01-openssl.bat
  - if not "%SOURCE%"=="TRUE" ci_scripts\02-opus.bat
  - if not "%SOURCE%"=="TRUE" ci_scripts\03-build.bat
  - if "%SOURCE%"=="TRUE" ci_scripts\04-source.bat

after_build:
  - ps: ls dist

deploy_script:
  - echo "Starting Artifact Deployment"
  # populate pypirc file for twine
  - echo [distutils]                                  > %USERPROFILE%\\.pypirc
  - echo index-servers =                             >> %USERPROFILE%\\.pypirc
  - echo     pypi                                    >> %USERPROFILE%\\.pypirc
  - echo [pypi]                                      >> %USERPROFILE%\\.pypirc
  - echo username=bakatrouble                        >> %USERPROFILE%\\.pypirc
  - echo password=%PYPI_PASSWORD%                    >> %USERPROFILE%\\.pypirc
  # upload to pypi for windows
  - set HOME=%USERPROFILE%
  - twine upload --skip-existing dist/* 2>$null
  - echo "Finished Artifact Deployment"

artifacts:
  - path: dist\*
